# Generated by Django 4.2.4 on 2023-08-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.TextField(default='No content available'),
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.TextField(default='No content available'),
        ),
    ]
